auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

comments :
    provider : duoshuo
    duoshuo :
      short_name : yaotec

title: Yaotec.info
url: http://Yaotec.info
feed: /atom.xml
author_info: <a href="http://Yaotec.info/">Yaotc</a>
